spring.application.name=report_builder

spring.datasource.url=jdbc:h2:file:C:/Users/${user.name}/categorytracker_bot;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

bot.token=8739771015:AAH0OeedCnRoTS8pmMd77Ur3HeYIpdO0LU8